lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET)%'
    public_key: ~
    pass_phrase: ~
    encoder:
        signature_algorithm: HS256
    token_ttl: '%app.jwt_ttl%'
    blocklist_token:
        enabled: true
        cache: cache.app
    token_extractors:
        authorization_header:
            enabled: false
        cookie:
            enabled: true
            name: access_token
    set_cookies:
        access_token:
            samesite: strict
            path: /
            domain: ~
            secure: false
            httpOnly: true

when@prod:
    lexik_jwt_authentication:
        set_cookies:
            access_token:
                secure: true
