security:
    password_hashers:
        App\Auth\Entity\User: 'auto'

    providers:
        app_users:
            entity:
                class: App\Auth\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_users
            json_login:
                check_path: api_auth_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            logout:
                path: api_auth_logout

    access_control:
        - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1,      roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            App\Auth\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
