when@dev: &dev
    zenstruck_foundry:
        persistence:
            flush_once: true

    services:
        App\Auth\DataFixtures\:
            resource: '%kernel.project_dir%/src/Auth/DataFixtures/'
            autowire: true
            autoconfigure: true

        App\Task\DataFixtures\:
            resource: '%kernel.project_dir%/src/Task/DataFixtures/'
            autowire: true
            autoconfigure: true

when@test: *dev
