when@dev: &dev
    zenstruck_foundry:
        persistence:
            flush_once: true

    services:
        App\Fixtures\:
            resource: '%kernel.project_dir%/fixtures/'
            autowire: true
            autoconfigure: true

when@test:
    zenstruck_foundry:
        orm:
            reset:
                mode: migrate

        persistence:
            flush_once: true

    services:
        App\Fixtures\:
            resource: '%kernel.project_dir%/fixtures/'
            autowire: true
            autoconfigure: true
