<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260403153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create audit_logs table.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE audit_logs (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT DEFAULT NULL,
                entity_type VARCHAR(50) NOT NULL,
                entity_id UUID NOT NULL,
                action VARCHAR(50) NOT NULL,
                message TEXT NOT NULL,
                attribute_changes JSONB DEFAULT NULL,
                properties JSONB DEFAULT NULL,
                created_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_audit_logs_entity_created_at ON audit_logs (entity_type, entity_id, created_at)');
        $this->addSql('CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id)');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_ACTIVITY_LOGS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('DROP TABLE audit_logs');
    }
}
