<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260331145539 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create task_status_changes table.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE task_status_changes (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                task_id INT NOT NULL,
                from_status VARCHAR(20) NOT NULL,
                to_status VARCHAR(20) NOT NULL,
                changed_at TIMESTAMPTZ NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_task_status_changes_task_changed_at ON task_status_changes (task_id, changed_at)');
        $this->addSql('COMMENT ON COLUMN task_status_changes.from_status IS \'(DC2Type:App\\Task\\Enum\\TaskStatus)\'');
        $this->addSql('COMMENT ON COLUMN task_status_changes.to_status IS \'(DC2Type:App\\Task\\Enum\\TaskStatus)\'');
        $this->addSql('ALTER TABLE task_status_changes ADD CONSTRAINT FK_TASK_STATUS_CHANGES_TASK FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('DROP TABLE task_status_changes');
    }
}
