<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004205220 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create workspaces and their members.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('CREATE TABLE workspace_members (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, workspace_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_workspace_members_user_id ON workspace_members (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_workspace_members_workspace_user ON workspace_members (workspace_id, user_id)');
        $this->addSql('CREATE INDEX IDX_9D9D39F482D40A1F ON workspace_members (workspace_id)');
        $this->addSql('CREATE TABLE workspaces (id UUID NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE workspace_members ADD CONSTRAINT FK_9D9D39F482D40A1F FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workspace_members ADD CONSTRAINT fk_workspace_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('ALTER TABLE workspace_members DROP CONSTRAINT FK_9D9D39F482D40A1F');
        $this->addSql('ALTER TABLE workspace_members DROP CONSTRAINT fk_workspace_members_user');
        $this->addSql('DROP TABLE workspace_members');
        $this->addSql('DROP TABLE workspaces');
    }
}
